image:     docker:stable

services:
  - docker:dind

stages:
  - build
  - test
  - cleaning

build:
  stage:   build
  script:
    - docker build -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE

test:
  stage:   test
  script:
    - docker pull $CI_REGISTRY_IMAGE
    - docker run --name $CI_REGISTRY_IMAGE $CI_REGISTRY_IMAGE

cleaning:
  stage:    cleaning
  script:
    - docker rm -f -v $CI_REGISTRY_IMAGE
  only:
    - master
