
image: docker:latest

services:
  - docker:dind

stages:
  - build
  - test

variables:
  APP: android-root-tools

build:
  stage: build
  script:
    - docker build -t ${APP} .
  only:
    - master

test:
  stage: test
  script:
    - docker run --name ${APP} ${APP}
  only:
    - master
