image:     docker:stable

services:
  - docker:dind

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

stages:
  - build
  - test

build:
  stage:   build
  script:
    - docker build -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE

test:
  stage:   test
  script:
    - docker pull $CI_REGISTRY_IMAGE
    - docker run --rm $CI_REGISTRY_IMAGE
  only:
    - master
