version: "3.7"

services:
  adb-fastboot:
    container_name: adb-fastboot
    image: alexandreoda/adb-fastboot
    volumes:
      - "${HOME}:/home/adb"
      - "/dev/bus/usb:/dev/bus/usb"
    ports:
      - "5037:5037"